/**
 * Thermal 80mm receipt PDF generation.
 * Width 80mm (~227 pt), variable height. Stored under uploads/receipts/.
 */

import path from "path";
import fs from "fs";
import PDFDocument from "pdfkit";
import { storage, findPaymentReceiptById } from "./storage";

const MM_TO_PT = 2.83465;
const WIDTH_MM = 80;
const WIDTH_PT = Math.round(WIDTH_MM * MM_TO_PT);
/** Exported for tests: thermal receipt width in points (80mm). */
export const RECEIPT_PDF_WIDTH_PT = WIDTH_PT;
const MARGIN = 10;
const LINE_HEIGHT = 12;
const FONT_SIZE = 9;
const LOGO_SIZE = 40;

const FALLBACK_ISSUER_NAME = process.env.RECEIPT_ISSUER_NAME || "POL263";
const FALLBACK_FOOTER_TEXT = process.env.RECEIPT_FOOTER_TEXT || "Thank you for your payment.";

import { resolveImage } from "./object-storage";
import * as objectStorage from "./object-storage";

async function resolveLogoForReceipt(logoUrl: string | null | undefined): Promise<Buffer | string | null> {
  return resolveImage(logoUrl);
}

export async function generateReceiptPdf(receiptId: string): Promise<string | null> {
  const receipt = await findPaymentReceiptById(receiptId);
  if (!receipt) return null;
  const orgId = receipt.organizationId;
  const policy = await storage.getPolicy(receipt.policyId, orgId);
  const client = await storage.getClient(receipt.clientId, orgId);
  const org = await storage.getOrganization(orgId);
  if (!policy || !client || !org) return null;

  const filename = `RCP-${receipt.receiptNumber.replace(/\s/g, "-")}-${receiptId.slice(0, 8)}.pdf`;

  const logoData = await resolveLogoForReceipt(org.logoUrl);

  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: [WIDTH_PT, 600], margin: MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));

    doc.fontSize(FONT_SIZE);
    let y = MARGIN;

    const line = (text: string, opts?: { bold?: boolean }) => {
      if (opts?.bold) doc.font("Helvetica-Bold");
      doc.text(text, MARGIN, y, { width: WIDTH_PT - 2 * MARGIN, align: "center" });
      if (opts?.bold) doc.font("Helvetica");
      y += LINE_HEIGHT;
    };
    const lineLeft = (text: string) => {
      doc.text(text, MARGIN, y, { width: WIDTH_PT - 2 * MARGIN });
      y += LINE_HEIGHT;
    };
    if (logoData) {
      try {
        const logoX = Math.round((WIDTH_PT - LOGO_SIZE) / 2);
        doc.image(logoData, logoX, y, { width: LOGO_SIZE, height: LOGO_SIZE });
        y += LOGO_SIZE + 4;
      } catch (_) { /* skip logo if unreadable */ }
    }

    const issuerName = org.name || FALLBACK_ISSUER_NAME;
    line(issuerName, { bold: true });
    if (org.address) line(org.address);
    const contactParts: string[] = [];
    if (org.phone) contactParts.push(`Tel: ${org.phone}`);
    if (org.email) contactParts.push(org.email);
    if (contactParts.length) line(contactParts.join(" | "));
    if (org.website) line(org.website);
    y += 4;
    line("PAYMENT RECEIPT", { bold: true });
    const displayReceiptNum = /^\d+$/.test(String(receipt.receiptNumber).trim())
      ? `RCP-${String(receipt.receiptNumber).padStart(5, "0")}`
      : receipt.receiptNumber;
    line(`Receipt # ${displayReceiptNum}`);
    const issuedDate = new Date(receipt.issuedAt);
    line(`Date: ${issuedDate.toLocaleDateString("en-GB")} ${issuedDate.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`);
    y += 6;

    lineLeft(`Client: ${client.firstName} ${client.lastName}`);
    if (client.phone) lineLeft(`Phone: ${client.phone}`);
    lineLeft(`Policy: ${policy.policyNumber}`);
    lineLeft(`Channel: ${receipt.paymentChannel}`);
    lineLeft(`Amount: ${receipt.currency} ${receipt.amount}`);
    const meta = receipt.metadataJson as Record<string, string> | null;
    if (meta?.paynowReference) lineLeft(`Paynow Ref: ${meta.paynowReference}`);
    y += 6;

    line(org.footerText || FALLBACK_FOOTER_TEXT);
    y += 8;
    const generatedAt = new Date();
    line(`Generated by ${issuerName}`);
    doc.fontSize(7);
    line(`${generatedAt.toLocaleDateString("en-GB")} ${generatedAt.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}`);

    doc.end();
    doc.on("end", async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const { key } = await objectStorage.uploadFile(pdfBuffer, filename, "application/pdf", "receipts");
        resolve(key);
      } catch {
        resolve(null);
      }
    });
    doc.on("error", () => resolve(null));
  });
}

/**
 * Resolve receipt PDF for download. Returns either a local file path (string)
 * or an object-storage Buffer, or null if not found.
 */
export async function getReceiptPdfPath(pdfStorageKey: string | null): Promise<string | Buffer | null> {
  if (!pdfStorageKey) return null;

  if (objectStorage.isObjectStorageEnabled) {
    const buf = await objectStorage.fetchFile(pdfStorageKey);
    if (buf) return buf;
  }

  const normalized = path.normalize(pdfStorageKey).replace(/^(\.\.(\/|\\))+/g, "");
  const full = path.resolve(process.cwd(), "uploads", normalized);
  return fs.existsSync(full) ? full : null;
}
