/**
 * Thermal 80mm receipt PDF generation.
 * Width 80mm (~227 pt), variable height. Stored under uploads/receipts/.
 */

import path from "path";
import fs from "fs";
import PDFDocument from "pdfkit";
import { storage, findPaymentReceiptById } from "./storage";

const MM_TO_PT = 2.83465;
const WIDTH_MM = 80;
const WIDTH_PT = Math.round(WIDTH_MM * MM_TO_PT);
/** Exported for tests: thermal receipt width in points (80mm). */
export const RECEIPT_PDF_WIDTH_PT = WIDTH_PT;
const MARGIN = 10;
const LINE_HEIGHT = 12;
const FONT_SIZE = 9;

const FALLBACK_ISSUER_NAME = process.env.RECEIPT_ISSUER_NAME || "POL263";
const FALLBACK_FOOTER_TEXT = process.env.RECEIPT_FOOTER_TEXT || "Thank you for your payment.";

export async function generateReceiptPdf(receiptId: string): Promise<string | null> {
  const receipt = await findPaymentReceiptById(receiptId);
  if (!receipt) return null;
  const orgId = receipt.organizationId;
  const policy = await storage.getPolicy(receipt.policyId, orgId);
  const client = await storage.getClient(receipt.clientId, orgId);
  const org = await storage.getOrganization(orgId);
  if (!policy || !client || !org) return null;

  const receiptsDir = path.resolve(process.cwd(), "uploads", "receipts");
  if (!fs.existsSync(receiptsDir)) fs.mkdirSync(receiptsDir, { recursive: true });
  const filename = `RCP-${receipt.receiptNumber.replace(/\s/g, "-")}-${receiptId.slice(0, 8)}.pdf`;
  const filepath = path.join(receiptsDir, filename);

  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: [WIDTH_PT, 600], margin: MARGIN, bufferPages: true });
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    doc.fontSize(FONT_SIZE);
    let y = MARGIN;

    const line = (text: string, opts?: { bold?: boolean }) => {
      if (opts?.bold) doc.font("Helvetica-Bold");
      doc.text(text, MARGIN, y, { width: WIDTH_PT - 2 * MARGIN, align: "center" });
      if (opts?.bold) doc.font("Helvetica");
      y += LINE_HEIGHT;
    };
    const lineLeft = (text: string) => {
      doc.text(text, MARGIN, y, { width: WIDTH_PT - 2 * MARGIN });
      y += LINE_HEIGHT;
    };

    const issuerName = org.name || FALLBACK_ISSUER_NAME;
    line(issuerName, { bold: true });
    if (org.address) line(org.address);
    const contactParts: string[] = [];
    if (org.phone) contactParts.push(`Tel: ${org.phone}`);
    if (org.email) contactParts.push(org.email);
    if (contactParts.length) line(contactParts.join(" | "));
    if (org.website) line(org.website);
    y += 4;
    line("PAYMENT RECEIPT", { bold: true });
    line(`Receipt # ${receipt.receiptNumber}`);
    line(`Date: ${new Date(receipt.issuedAt).toLocaleString()}`);
    y += 6;

    lineLeft(`Client: ${client.firstName} ${client.lastName}`);
    if (client.phone) lineLeft(`Phone: ${client.phone}`);
    lineLeft(`Policy: ${policy.policyNumber}`);
    lineLeft(`Channel: ${receipt.paymentChannel}`);
    lineLeft(`Amount: ${receipt.currency} ${receipt.amount}`);
    const meta = receipt.metadataJson as Record<string, string> | null;
    if (meta?.paynowReference) lineLeft(`Paynow Ref: ${meta.paynowReference}`);
    y += 6;

    line(org.footerText || FALLBACK_FOOTER_TEXT);
    y += 8;
    line(`Generated by ${issuerName}`);

    doc.end();
    stream.on("finish", () => {
      const relativeKey = path.join("receipts", filename).replace(/\\/g, "/");
      resolve(relativeKey);
    });
    stream.on("error", () => resolve(null));
  });
}

/** Resolve PDF path for download (uploads/receipts/... or receipts/...). */
export function getReceiptPdfPath(pdfStorageKey: string | null): string | null {
  if (!pdfStorageKey) return null;
  const normalized = path.normalize(pdfStorageKey).replace(/^(\.\.(\/|\\))+/g, "");
  const full = path.resolve(process.cwd(), "uploads", normalized);
  return fs.existsSync(full) ? full : null;
}
